version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: vcard-reverse-proxy
    ports:
      - "7777:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:7777/api
    container_name: vcard-frontend
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:7777/api

  backend:
    build: ./backend
    container_name: vcard-backend
    expose:
      - "4000"
    volumes:
      - ./data:/app/data
    environment:
      DATABASE_PATH: /app/data/db.sqlite
